version: "1.0"
info:
  model: int-scaffold
packages:
- name: EdgeICUI_AutomaionProject0913
  gitServerName: ICAccount0913
  gitUrl: https://github.com/MeghaRaj69/EdgeICUI_AutomaionProject0913
  gitUsername: MeghaRaj69
  gitToken: edge.scaffolding.EdgeICUI_AutomaionProject0913.ICAccount0913.gitToken
  gitBranch: main
